#!/usr/bin/env bash

me="$(basename "$0")";
running=$(ps h -C "$me" | grep -wv $$ | wc -l);
[[ $running > 1 ]] && exit;

time=4

off=$(amixer get Master | grep -o "off" | head -n 1)

if [[ "$1" == "mute" || "$off" == *"off"* ]]
then
    echo `amixer set Master toggle` > /dev/null
fi

if [[ "$1" == "lower" ]]
then
    #echo `amixer set Master 5%-` > /dev/null
    delta=-10%
elif [[ "$1" == "raise" ]]
then
    #echo `amixer set Master 5%+` > /dev/null
    delta=+10%
fi

#pactl set-sink-volume @DEFAULT_SINK@ $delta
getdefaultsinkname() {
    pacmd stat | awk -F": " '/^Default sink name: /{print $2}'
}

getdefaultsinkvol() {
    pacmd list-sinks |
    awk '/^\s+name: /{indefault = $2 == "<'$(getdefaultsinkname)'>"}/^\s+volume: / && indefault {print $5; exit}'
}

setallsinks() {
    echo "Setting all sink volumes to $1"
    for SINK in `pacmd list-sinks | grep 'index:' | cut -b12-`
    do
      pactl set-sink-volume $SINK $1
    done
}
echo Getting default sink volume: 
v=$(getdefaultsinkvol)
setallsinks $v
vol=$(amixer get Master | grep -Po "[0-9]+(?=%)" | tail -1)
off=$(amixer get Master | grep -o "off" | head -n 1)

alpha="0.5"

if [[ "$1" == "mute" && "$off" == *"off"* ]]
then
    avizo-client --image-resource="volume_muted" --progress="0" --time=$time --background="rgba(255, 255, 255, $alpha)"
else
    scaled=$(echo "scale=2; $vol / 100.0" | bc)
    echo $scaled

    if [ "$vol" -lt "34" ]
    then
        avizo-client --image-resource="volume_low" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
    elif [ "$vol" -lt "67" ]
    then
        avizo-client --image-resource="volume_medium" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
    elif [ "$vol" -lt "101" ]
    then
        avizo-client --image-resource="volume_high" --progress=$scaled --time=$time --background="rgba(255, 255, 255, $alpha)"
    fi
fi

